# Generated by Django 3.0.7 on 2021-01-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzone_app', '0002_admin_customer_servicerequest_customer_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='servicerequest_customer',
            new_name='servicerequestcustomer',
        ),
    ]
