# Generated by Django 3.0.7 on 2021-01-21 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzone_app', '0003_auto_20210121_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='admin',
        ),
        migrations.AlterField(
            model_name='servicerequestcustomer',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='staff',
        ),
    ]
