# Generated by Django 3.0.7 on 2021-01-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzone_app', '0004_auto_20210122_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='servicerequestcustomer',
        ),
    ]
