# Generated by Django 3.0.7 on 2021-01-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzone_app', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='offlinecustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('vehicle', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('regno', models.TextField()),
                ('location', models.TextField()),
                ('services', models.TextField()),
                ('phonenumber', models.TextField()),
                ('service_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
