# Generated by Django 3.0.7 on 2021-01-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzone_app', '0009_salesreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salesreport',
        ),
    ]
