# Generated by Django 3.0.7 on 2021-02-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzone_app', '0011_salesreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='parts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('partname', models.TextField()),
                ('sellername', models.TextField()),
                ('companyname', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.TextField()),
                ('cost', models.TextField()),
                ('gst', models.TextField()),
            ],
        ),
    ]
